__author__ = "Md. Sabuj Sarker"
__copyright__ = "Copyright 2017-2018, The Synamic Project"
__credits__ = ["Md. Sabuj Sarker"]
__license__ = "MIT"
__version__ = "0.1.dev"
__maintainer__ = "Md. Sabuj Sarker"
__email__ = "md.sabuj.sarker@gmail.com"
__status__ = "Development"
"""
author: "Md. Sabuj Sarker"
copyright: "Copyright 2017-2018, The Synamic Project"
credits: ["Md. Sabuj Sarker"]
license: "MIT"
maintainer: "Md. Sabuj Sarker"
email: "md.sabuj.sarker@gmail.com"
status: "Development"
"""